// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

// InitializeApp creates and wires all dependencies
func InitializeApp() *UserService {
	logger := NewLogger()
	database := NewDatabase(logger)
	userRepository := NewUserRepository(database)
	printerService := NewPrinterService(logger)
	userService := NewUserService(userRepository, printerService, logger)
	return userService
}
