// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Person.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Place int32

const (
	Place_UNSET         Place = 0
	Place_MOSCOW        Place = 1
	Place_ST_PETERSBURG Place = 2
)

var Place_name = map[int32]string{
	0: "UNSET",
	1: "MOSCOW",
	2: "ST_PETERSBURG",
}

var Place_value = map[string]int32{
	"UNSET":         0,
	"MOSCOW":        1,
	"ST_PETERSBURG": 2,
}

func (x Place) String() string {
	return proto.EnumName(Place_name, int32(x))
}

func (Place) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_841ab6396175eaf3, []int{0}
}

type People struct {
	Person               []*Person `protobuf:"bytes,1,rep,name=person,proto3" json:"person,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *People) Reset()         { *m = People{} }
func (m *People) String() string { return proto.CompactTextString(m) }
func (*People) ProtoMessage()    {}
func (*People) Descriptor() ([]byte, []int) {
	return fileDescriptor_841ab6396175eaf3, []int{0}
}

func (m *People) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_People.Unmarshal(m, b)
}
func (m *People) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_People.Marshal(b, m, deterministic)
}
func (m *People) XXX_Merge(src proto.Message) {
	xxx_messageInfo_People.Merge(m, src)
}
func (m *People) XXX_Size() int {
	return xxx_messageInfo_People.Size(m)
}
func (m *People) XXX_DiscardUnknown() {
	xxx_messageInfo_People.DiscardUnknown(m)
}

var xxx_messageInfo_People proto.InternalMessageInfo

func (m *People) GetPerson() []*Person {
	if m != nil {
		return m.Person
	}
	return nil
}

type Person struct {
	Name                 string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Mobile               []string             `protobuf:"bytes,3,rep,name=mobile,proto3" json:"mobile,omitempty"`
	Email                []string             `protobuf:"bytes,4,rep,name=email,proto3" json:"email,omitempty"`
	Place                Place                `protobuf:"varint,5,opt,name=place,proto3,enum=main.Place" json:"place,omitempty"`
	T                    *timestamp.Timestamp `protobuf:"bytes,6,opt,name=t,proto3" json:"t,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_841ab6396175eaf3, []int{1}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetMobile() []string {
	if m != nil {
		return m.Mobile
	}
	return nil
}

func (m *Person) GetEmail() []string {
	if m != nil {
		return m.Email
	}
	return nil
}

func (m *Person) GetPlace() Place {
	if m != nil {
		return m.Place
	}
	return Place_UNSET
}

func (m *Person) GetT() *timestamp.Timestamp {
	if m != nil {
		return m.T
	}
	return nil
}

type Address struct {
	Street               string   `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	Number               int32    `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_841ab6396175eaf3, []int{2}
}

func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetStreet() string {
	if m != nil {
		return m.Street
	}
	return ""
}

func (m *Address) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func init() {
	proto.RegisterEnum("main.Place", Place_name, Place_value)
	proto.RegisterType((*People)(nil), "main.People")
	proto.RegisterType((*Person)(nil), "main.Person")
	proto.RegisterType((*Address)(nil), "main.Address")
}

func init() { proto.RegisterFile("Person.proto", fileDescriptor_841ab6396175eaf3) }

var fileDescriptor_841ab6396175eaf3 = []byte{
	// 285 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8f, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x71, 0xdb, 0x18, 0xf5, 0x5a, 0x50, 0xb1, 0x10, 0xb2, 0xba, 0x60, 0x2a, 0x06, 0x8b,
	0xc1, 0x15, 0x65, 0x62, 0x04, 0x54, 0x31, 0x41, 0x2b, 0x27, 0x15, 0x23, 0x4a, 0xe8, 0x51, 0x45,
	0x8a, 0xe3, 0x28, 0x71, 0x7f, 0x0b, 0x7f, 0x17, 0xd9, 0x71, 0xb7, 0x7b, 0xdf, 0xd9, 0xef, 0xde,
	0x83, 0xe9, 0x16, 0xdb, 0xce, 0xd6, 0xaa, 0x69, 0xad, 0xb3, 0x6c, 0x64, 0xf2, 0xb2, 0x9e, 0xdf,
	0x1e, 0xac, 0x3d, 0x54, 0xb8, 0x0c, 0xac, 0x38, 0xfe, 0x2e, 0x5d, 0x69, 0xb0, 0x73, 0xb9, 0x69,
	0xfa, 0x67, 0x0b, 0x05, 0x74, 0x8b, 0xb6, 0xa9, 0x90, 0xdd, 0x03, 0x6d, 0x82, 0x01, 0x27, 0x62,
	0x28, 0x27, 0xab, 0xa9, 0xf2, 0x0e, 0xaa, 0x37, 0xd5, 0x71, 0xb7, 0xf8, 0x23, 0xfe, 0x83, 0x1f,
	0x19, 0x83, 0x51, 0x9d, 0x1b, 0xe4, 0x44, 0x10, 0x39, 0xd6, 0x61, 0x66, 0x37, 0x40, 0x8d, 0x2d,
	0xca, 0x0a, 0xf9, 0x50, 0x0c, 0xe5, 0x58, 0x47, 0xc5, 0xae, 0x21, 0x41, 0x93, 0x97, 0x15, 0x1f,
	0x05, 0xdc, 0x0b, 0x76, 0x07, 0x49, 0x53, 0xe5, 0x3f, 0xc8, 0x13, 0x41, 0xe4, 0xe5, 0x6a, 0x12,
	0x2f, 0x7a, 0xa4, 0xfb, 0x0d, 0x93, 0x40, 0x1c, 0xa7, 0x82, 0xc8, 0xc9, 0x6a, 0xae, 0xfa, 0x32,
	0xea, 0x54, 0x46, 0x65, 0xa7, 0x32, 0x9a, 0xb8, 0xc5, 0x33, 0x9c, 0xbf, 0xec, 0xf7, 0x2d, 0x76,
	0x9d, 0x4f, 0xd1, 0xb9, 0x16, 0xd1, 0xc5, 0x6c, 0x51, 0x79, 0x5e, 0x1f, 0x4d, 0x81, 0x2d, 0x1f,
	0x08, 0x22, 0x13, 0x1d, 0xd5, 0xc3, 0x23, 0x24, 0xe1, 0x28, 0x1b, 0x43, 0xb2, 0xfb, 0x4c, 0xd7,
	0xd9, 0xec, 0x8c, 0x01, 0xd0, 0x8f, 0x4d, 0xfa, 0xb6, 0xf9, 0x9a, 0x11, 0x76, 0x05, 0x17, 0x69,
	0xf6, 0xbd, 0x5d, 0x67, 0x6b, 0x9d, 0xbe, 0xee, 0xf4, 0xfb, 0x6c, 0x50, 0xd0, 0x10, 0xe2, 0xe9,
	0x3f, 0x00, 0x00, 0xff, 0xff, 0xd3, 0x4c, 0x2d, 0xb8, 0x75, 0x01, 0x00, 0x00,
}
