// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.6.1
// source: elections.proto

package pb

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmitVoteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vote *SubmitVoteRequest_Vote `protobuf:"bytes,1,opt,name=vote,proto3" json:"vote,omitempty"`
}

func (x *SubmitVoteRequest) Reset() {
	*x = SubmitVoteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_elections_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitVoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitVoteRequest) ProtoMessage() {}

func (x *SubmitVoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_elections_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitVoteRequest.ProtoReflect.Descriptor instead.
func (*SubmitVoteRequest) Descriptor() ([]byte, []int) {
	return file_elections_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitVoteRequest) GetVote() *SubmitVoteRequest_Vote {
	if x != nil {
		return x.Vote
	}
	return nil
}

type SubmitVoteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SubmitVoteResponse) Reset() {
	*x = SubmitVoteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_elections_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitVoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitVoteResponse) ProtoMessage() {}

func (x *SubmitVoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_elections_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitVoteResponse.ProtoReflect.Descriptor instead.
func (*SubmitVoteResponse) Descriptor() ([]byte, []int) {
	return file_elections_proto_rawDescGZIP(), []int{1}
}

type SubmitVoteRequest_Vote struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Passport    string               `protobuf:"bytes,1,opt,name=passport,proto3" json:"passport,omitempty"`
	CandidateId uint32               `protobuf:"varint,2,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	Note        string               `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	Time        *timestamp.Timestamp `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *SubmitVoteRequest_Vote) Reset() {
	*x = SubmitVoteRequest_Vote{}
	if protoimpl.UnsafeEnabled {
		mi := &file_elections_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitVoteRequest_Vote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitVoteRequest_Vote) ProtoMessage() {}

func (x *SubmitVoteRequest_Vote) ProtoReflect() protoreflect.Message {
	mi := &file_elections_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitVoteRequest_Vote.ProtoReflect.Descriptor instead.
func (*SubmitVoteRequest_Vote) Descriptor() ([]byte, []int) {
	return file_elections_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SubmitVoteRequest_Vote) GetPassport() string {
	if x != nil {
		return x.Passport
	}
	return ""
}

func (x *SubmitVoteRequest_Vote) GetCandidateId() uint32 {
	if x != nil {
		return x.CandidateId
	}
	return 0
}

func (x *SubmitVoteRequest_Vote) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *SubmitVoteRequest_Vote) GetTime() *timestamp.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

var File_elections_proto protoreflect.FileDescriptor

var file_elections_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd6, 0x01,
	0x0a, 0x11, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x56, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x04, 0x76, 0x6f, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x21, 0x2e, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x53, 0x75,
	0x62, 0x6d, 0x69, 0x74, 0x56, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e,
	0x56, 0x6f, 0x74, 0x65, 0x52, 0x04, 0x76, 0x6f, 0x74, 0x65, 0x1a, 0x89, 0x01, 0x0a, 0x04, 0x56,
	0x6f, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x12,
	0x21, 0x0a, 0x0c, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x14, 0x0a, 0x12, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74,
	0x56, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x58, 0x0a, 0x09,
	0x45, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x4b, 0x0a, 0x0a, 0x53, 0x75, 0x62,
	0x6d, 0x69, 0x74, 0x56, 0x6f, 0x74, 0x65, 0x12, 0x1c, 0x2e, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x56, 0x6f, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x56, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_elections_proto_rawDescOnce sync.Once
	file_elections_proto_rawDescData = file_elections_proto_rawDesc
)

func file_elections_proto_rawDescGZIP() []byte {
	file_elections_proto_rawDescOnce.Do(func() {
		file_elections_proto_rawDescData = protoimpl.X.CompressGZIP(file_elections_proto_rawDescData)
	})
	return file_elections_proto_rawDescData
}

var file_elections_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_elections_proto_goTypes = []interface{}{
	(*SubmitVoteRequest)(nil),      // 0: elections.SubmitVoteRequest
	(*SubmitVoteResponse)(nil),     // 1: elections.SubmitVoteResponse
	(*SubmitVoteRequest_Vote)(nil), // 2: elections.SubmitVoteRequest.Vote
	(*timestamp.Timestamp)(nil),    // 3: google.protobuf.Timestamp
}
var file_elections_proto_depIdxs = []int32{
	2, // 0: elections.SubmitVoteRequest.vote:type_name -> elections.SubmitVoteRequest.Vote
	3, // 1: elections.SubmitVoteRequest.Vote.time:type_name -> google.protobuf.Timestamp
	0, // 2: elections.Elections.SubmitVote:input_type -> elections.SubmitVoteRequest
	1, // 3: elections.Elections.SubmitVote:output_type -> elections.SubmitVoteResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_elections_proto_init() }
func file_elections_proto_init() {
	if File_elections_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_elections_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmitVoteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_elections_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmitVoteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_elections_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmitVoteRequest_Vote); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_elections_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_elections_proto_goTypes,
		DependencyIndexes: file_elections_proto_depIdxs,
		MessageInfos:      file_elections_proto_msgTypes,
	}.Build()
	File_elections_proto = out.File
	file_elections_proto_rawDesc = nil
	file_elections_proto_goTypes = nil
	file_elections_proto_depIdxs = nil
}
