// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: elections.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmitVoteRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Vote          *SubmitVoteRequest_Vote `protobuf:"bytes,1,opt,name=vote,proto3" json:"vote,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitVoteRequest) Reset() {
	*x = SubmitVoteRequest{}
	mi := &file_elections_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitVoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitVoteRequest) ProtoMessage() {}

func (x *SubmitVoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_elections_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitVoteRequest.ProtoReflect.Descriptor instead.
func (*SubmitVoteRequest) Descriptor() ([]byte, []int) {
	return file_elections_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitVoteRequest) GetVote() *SubmitVoteRequest_Vote {
	if x != nil {
		return x.Vote
	}
	return nil
}

type SubmitVoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitVoteResponse) Reset() {
	*x = SubmitVoteResponse{}
	mi := &file_elections_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitVoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitVoteResponse) ProtoMessage() {}

func (x *SubmitVoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_elections_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitVoteResponse.ProtoReflect.Descriptor instead.
func (*SubmitVoteResponse) Descriptor() ([]byte, []int) {
	return file_elections_proto_rawDescGZIP(), []int{1}
}

type SubmitVoteRequest_Vote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Passport      string                 `protobuf:"bytes,1,opt,name=passport,proto3" json:"passport,omitempty"`
	CandidateId   uint32                 `protobuf:"varint,2,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	Note          string                 `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitVoteRequest_Vote) Reset() {
	*x = SubmitVoteRequest_Vote{}
	mi := &file_elections_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitVoteRequest_Vote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitVoteRequest_Vote) ProtoMessage() {}

func (x *SubmitVoteRequest_Vote) ProtoReflect() protoreflect.Message {
	mi := &file_elections_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitVoteRequest_Vote.ProtoReflect.Descriptor instead.
func (*SubmitVoteRequest_Vote) Descriptor() ([]byte, []int) {
	return file_elections_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SubmitVoteRequest_Vote) GetPassport() string {
	if x != nil {
		return x.Passport
	}
	return ""
}

func (x *SubmitVoteRequest_Vote) GetCandidateId() uint32 {
	if x != nil {
		return x.CandidateId
	}
	return 0
}

func (x *SubmitVoteRequest_Vote) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *SubmitVoteRequest_Vote) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

var File_elections_proto protoreflect.FileDescriptor

const file_elections_proto_rawDesc = "" +
	"\n" +
	"\x0felections.proto\x12\telections\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd6\x01\n" +
	"\x11SubmitVoteRequest\x125\n" +
	"\x04vote\x18\x01 \x01(\v2!.elections.SubmitVoteRequest.VoteR\x04vote\x1a\x89\x01\n" +
	"\x04Vote\x12\x1a\n" +
	"\bpassport\x18\x01 \x01(\tR\bpassport\x12!\n" +
	"\fcandidate_id\x18\x02 \x01(\rR\vcandidateId\x12\x12\n" +
	"\x04note\x18\x03 \x01(\tR\x04note\x12.\n" +
	"\x04time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\"\x14\n" +
	"\x12SubmitVoteResponse2X\n" +
	"\tElections\x12K\n" +
	"\n" +
	"SubmitVote\x12\x1c.elections.SubmitVoteRequest\x1a\x1d.elections.SubmitVoteResponse\"\x00B\aZ\x05./;pbb\x06proto3"

var (
	file_elections_proto_rawDescOnce sync.Once
	file_elections_proto_rawDescData []byte
)

func file_elections_proto_rawDescGZIP() []byte {
	file_elections_proto_rawDescOnce.Do(func() {
		file_elections_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_elections_proto_rawDesc), len(file_elections_proto_rawDesc)))
	})
	return file_elections_proto_rawDescData
}

var file_elections_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_elections_proto_goTypes = []any{
	(*SubmitVoteRequest)(nil),      // 0: elections.SubmitVoteRequest
	(*SubmitVoteResponse)(nil),     // 1: elections.SubmitVoteResponse
	(*SubmitVoteRequest_Vote)(nil), // 2: elections.SubmitVoteRequest.Vote
	(*timestamppb.Timestamp)(nil),  // 3: google.protobuf.Timestamp
}
var file_elections_proto_depIdxs = []int32{
	2, // 0: elections.SubmitVoteRequest.vote:type_name -> elections.SubmitVoteRequest.Vote
	3, // 1: elections.SubmitVoteRequest.Vote.time:type_name -> google.protobuf.Timestamp
	0, // 2: elections.Elections.SubmitVote:input_type -> elections.SubmitVoteRequest
	1, // 3: elections.Elections.SubmitVote:output_type -> elections.SubmitVoteResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_elections_proto_init() }
func file_elections_proto_init() {
	if File_elections_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_elections_proto_rawDesc), len(file_elections_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_elections_proto_goTypes,
		DependencyIndexes: file_elections_proto_depIdxs,
		MessageInfos:      file_elections_proto_msgTypes,
	}.Build()
	File_elections_proto = out.File
	file_elections_proto_goTypes = nil
	file_elections_proto_depIdxs = nil
}
