// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: elections.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Elections_SubmitVote_FullMethodName = "/elections_with_admin.Elections/SubmitVote"
	Elections_Internal_FullMethodName   = "/elections_with_admin.Elections/Internal"
)

// ElectionsClient is the client API for Elections service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ElectionsClient interface {
	SubmitVote(ctx context.Context, in *Vote, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Internal(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Vote, StatsVote], error)
}

type electionsClient struct {
	cc grpc.ClientConnInterface
}

func NewElectionsClient(cc grpc.ClientConnInterface) ElectionsClient {
	return &electionsClient{cc}
}

func (c *electionsClient) SubmitVote(ctx context.Context, in *Vote, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Elections_SubmitVote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *electionsClient) Internal(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Vote, StatsVote], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Elections_ServiceDesc.Streams[0], Elections_Internal_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Vote, StatsVote]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Elections_InternalClient = grpc.BidiStreamingClient[Vote, StatsVote]

// ElectionsServer is the server API for Elections service.
// All implementations must embed UnimplementedElectionsServer
// for forward compatibility.
type ElectionsServer interface {
	SubmitVote(context.Context, *Vote) (*emptypb.Empty, error)
	Internal(grpc.BidiStreamingServer[Vote, StatsVote]) error
	mustEmbedUnimplementedElectionsServer()
}

// UnimplementedElectionsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedElectionsServer struct{}

func (UnimplementedElectionsServer) SubmitVote(context.Context, *Vote) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitVote not implemented")
}
func (UnimplementedElectionsServer) Internal(grpc.BidiStreamingServer[Vote, StatsVote]) error {
	return status.Errorf(codes.Unimplemented, "method Internal not implemented")
}
func (UnimplementedElectionsServer) mustEmbedUnimplementedElectionsServer() {}
func (UnimplementedElectionsServer) testEmbeddedByValue()                   {}

// UnsafeElectionsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ElectionsServer will
// result in compilation errors.
type UnsafeElectionsServer interface {
	mustEmbedUnimplementedElectionsServer()
}

func RegisterElectionsServer(s grpc.ServiceRegistrar, srv ElectionsServer) {
	// If the following call pancis, it indicates UnimplementedElectionsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Elections_ServiceDesc, srv)
}

func _Elections_SubmitVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Vote)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ElectionsServer).SubmitVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Elections_SubmitVote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ElectionsServer).SubmitVote(ctx, req.(*Vote))
	}
	return interceptor(ctx, in, info, handler)
}

func _Elections_Internal_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ElectionsServer).Internal(&grpc.GenericServerStream[Vote, StatsVote]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Elections_InternalServer = grpc.BidiStreamingServer[Vote, StatsVote]

// Elections_ServiceDesc is the grpc.ServiceDesc for Elections service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Elections_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "elections_with_admin.Elections",
	HandlerType: (*ElectionsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitVote",
			Handler:    _Elections_SubmitVote_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Internal",
			Handler:       _Elections_Internal_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "elections.proto",
}
