// Code generated by protoc-gen-go. DO NOT EDIT.
// source: elections.proto

package main

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Vote struct {
	Passport             string               `protobuf:"bytes,1,opt,name=passport,proto3" json:"passport,omitempty"`
	CandidateId          uint32               `protobuf:"varint,2,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	Note                 string               `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	Time                 *timestamp.Timestamp `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Vote) Reset()         { *m = Vote{} }
func (m *Vote) String() string { return proto.CompactTextString(m) }
func (*Vote) ProtoMessage()    {}
func (*Vote) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a2d3077d176f007, []int{0}
}

func (m *Vote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vote.Unmarshal(m, b)
}
func (m *Vote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vote.Marshal(b, m, deterministic)
}
func (m *Vote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vote.Merge(m, src)
}
func (m *Vote) XXX_Size() int {
	return xxx_messageInfo_Vote.Size(m)
}
func (m *Vote) XXX_DiscardUnknown() {
	xxx_messageInfo_Vote.DiscardUnknown(m)
}

var xxx_messageInfo_Vote proto.InternalMessageInfo

func (m *Vote) GetPassport() string {
	if m != nil {
		return m.Passport
	}
	return ""
}

func (m *Vote) GetCandidateId() uint32 {
	if m != nil {
		return m.CandidateId
	}
	return 0
}

func (m *Vote) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

func (m *Vote) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

type Stats struct {
	Records              map[uint32]uint32    `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Time                 *timestamp.Timestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Stats) Reset()         { *m = Stats{} }
func (m *Stats) String() string { return proto.CompactTextString(m) }
func (*Stats) ProtoMessage()    {}
func (*Stats) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a2d3077d176f007, []int{1}
}

func (m *Stats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stats.Unmarshal(m, b)
}
func (m *Stats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stats.Marshal(b, m, deterministic)
}
func (m *Stats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stats.Merge(m, src)
}
func (m *Stats) XXX_Size() int {
	return xxx_messageInfo_Stats.Size(m)
}
func (m *Stats) XXX_DiscardUnknown() {
	xxx_messageInfo_Stats.DiscardUnknown(m)
}

var xxx_messageInfo_Stats proto.InternalMessageInfo

func (m *Stats) GetRecords() map[uint32]uint32 {
	if m != nil {
		return m.Records
	}
	return nil
}

func (m *Stats) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

type StatsVote struct {
	// Types that are valid to be assigned to Body:
	//	*StatsVote_Stats
	//	*StatsVote_Vote
	Body                 isStatsVote_Body `protobuf_oneof:"body"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *StatsVote) Reset()         { *m = StatsVote{} }
func (m *StatsVote) String() string { return proto.CompactTextString(m) }
func (*StatsVote) ProtoMessage()    {}
func (*StatsVote) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a2d3077d176f007, []int{2}
}

func (m *StatsVote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatsVote.Unmarshal(m, b)
}
func (m *StatsVote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatsVote.Marshal(b, m, deterministic)
}
func (m *StatsVote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatsVote.Merge(m, src)
}
func (m *StatsVote) XXX_Size() int {
	return xxx_messageInfo_StatsVote.Size(m)
}
func (m *StatsVote) XXX_DiscardUnknown() {
	xxx_messageInfo_StatsVote.DiscardUnknown(m)
}

var xxx_messageInfo_StatsVote proto.InternalMessageInfo

type isStatsVote_Body interface {
	isStatsVote_Body()
}

type StatsVote_Stats struct {
	Stats *Stats `protobuf:"bytes,1,opt,name=stats,proto3,oneof"`
}

type StatsVote_Vote struct {
	Vote *Vote `protobuf:"bytes,2,opt,name=vote,proto3,oneof"`
}

func (*StatsVote_Stats) isStatsVote_Body() {}

func (*StatsVote_Vote) isStatsVote_Body() {}

func (m *StatsVote) GetBody() isStatsVote_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *StatsVote) GetStats() *Stats {
	if x, ok := m.GetBody().(*StatsVote_Stats); ok {
		return x.Stats
	}
	return nil
}

func (m *StatsVote) GetVote() *Vote {
	if x, ok := m.GetBody().(*StatsVote_Vote); ok {
		return x.Vote
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*StatsVote) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*StatsVote_Stats)(nil),
		(*StatsVote_Vote)(nil),
	}
}

func init() {
	proto.RegisterType((*Vote)(nil), "Vote")
	proto.RegisterType((*Stats)(nil), "Stats")
	proto.RegisterMapType((map[uint32]uint32)(nil), "Stats.RecordsEntry")
	proto.RegisterType((*StatsVote)(nil), "StatsVote")
}

func init() {
	proto.RegisterFile("elections.proto", fileDescriptor_1a2d3077d176f007)
}

var fileDescriptor_1a2d3077d176f007 = []byte{
	// 361 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xc1, 0x6e, 0xa3, 0x30,
	0x18, 0x84, 0x71, 0x02, 0x6c, 0xf2, 0x93, 0x68, 0x57, 0xde, 0xd5, 0x0a, 0x11, 0x69, 0x97, 0xd2,
	0x0b, 0x97, 0x38, 0x15, 0xbd, 0x54, 0x39, 0x46, 0x8a, 0x94, 0xdc, 0x2a, 0xa7, 0xea, 0xa1, 0x97,
	0xc8, 0x04, 0x37, 0x42, 0x05, 0x8c, 0xc0, 0x89, 0xc4, 0x23, 0xf4, 0x35, 0xfa, 0xa4, 0x15, 0x76,
	0x40, 0x55, 0x7b, 0xe9, 0xcd, 0x33, 0x9e, 0xb1, 0xbf, 0xdf, 0x86, 0x9f, 0x3c, 0xe3, 0x07, 0x99,
	0x8a, 0xa2, 0x26, 0x65, 0x25, 0xa4, 0xf0, 0xfe, 0x1f, 0x85, 0x38, 0x66, 0x7c, 0xa1, 0x54, 0x7c,
	0x7a, 0x5e, 0xc8, 0x34, 0xe7, 0xb5, 0x64, 0x79, 0x79, 0x09, 0xcc, 0x3e, 0x07, 0x78, 0x5e, 0xca,
	0x46, 0x6f, 0x06, 0xaf, 0x08, 0xcc, 0x47, 0x21, 0x39, 0xf6, 0x60, 0x54, 0xb2, 0xba, 0x2e, 0x45,
	0x25, 0x5d, 0xe4, 0xa3, 0x70, 0x4c, 0x7b, 0x8d, 0xaf, 0x60, 0x72, 0x60, 0x45, 0x92, 0x26, 0x4c,
	0xf2, 0x7d, 0x9a, 0xb8, 0x03, 0x1f, 0x85, 0x53, 0xea, 0xf4, 0xde, 0x36, 0xc1, 0x18, 0xcc, 0x42,
	0x48, 0xee, 0x0e, 0x55, 0x55, 0xad, 0x31, 0x01, 0xb3, 0x65, 0x71, 0x4d, 0x1f, 0x85, 0x4e, 0xe4,
	0x11, 0xcd, 0x41, 0x3a, 0x0e, 0xf2, 0xd0, 0x81, 0x52, 0x95, 0x0b, 0xde, 0x10, 0x58, 0x3b, 0xc9,
	0x64, 0x8d, 0xe7, 0xf0, 0xa3, 0xe2, 0x07, 0x51, 0x25, 0xb5, 0x8b, 0xfc, 0x61, 0xe8, 0x44, 0xbf,
	0x89, 0xda, 0x20, 0x54, 0xbb, 0xeb, 0x42, 0x56, 0x0d, 0xed, 0x32, 0xfd, 0x45, 0x83, 0xef, 0x5d,
	0xe4, 0x2d, 0x61, 0xf2, 0xf1, 0x20, 0xfc, 0x0b, 0x86, 0x2f, 0xbc, 0x51, 0x63, 0x4f, 0x69, 0xbb,
	0xc4, 0x7f, 0xc0, 0x3a, 0xb3, 0xec, 0xc4, 0x2f, 0xa3, 0x6a, 0xb1, 0x1c, 0xdc, 0xa1, 0xe0, 0x1e,
	0xc6, 0x0a, 0x45, 0x3d, 0xda, 0x3f, 0xb0, 0xea, 0x56, 0xa8, 0xaa, 0x13, 0xd9, 0x9a, 0x72, 0x63,
	0x50, 0x6d, 0xe3, 0x19, 0x98, 0xe7, 0xf6, 0x55, 0x34, 0x98, 0x45, 0xda, 0xd2, 0xc6, 0xa0, 0xca,
	0x5c, 0xd9, 0x60, 0xc6, 0x22, 0x69, 0xa2, 0x3d, 0x8c, 0xd7, 0xdd, 0x9f, 0xe2, 0x39, 0xc0, 0xee,
	0x14, 0xe7, 0xa9, 0x54, 0xe7, 0xeb, 0x86, 0xf7, 0xf7, 0xcb, 0x44, 0xeb, 0xf6, 0x0b, 0x03, 0x03,
	0x5f, 0xc3, 0x68, 0x5b, 0x48, 0x5e, 0x15, 0x2c, 0xeb, 0xc2, 0x40, 0x7a, 0xbe, 0xc0, 0x08, 0xd1,
	0x0d, 0x5a, 0xd9, 0x4f, 0x66, 0xce, 0xd2, 0x22, 0xb6, 0x55, 0xfd, 0xf6, 0x3d, 0x00, 0x00, 0xff,
	0xff, 0xa6, 0xc9, 0x91, 0x14, 0x43, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ElectionsClient is the client API for Elections service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ElectionsClient interface {
	SubmitVote(ctx context.Context, in *Vote, opts ...grpc.CallOption) (*empty.Empty, error)
	Internal(ctx context.Context, opts ...grpc.CallOption) (Elections_InternalClient, error)
}

type electionsClient struct {
	cc grpc.ClientConnInterface
}

func NewElectionsClient(cc grpc.ClientConnInterface) ElectionsClient {
	return &electionsClient{cc}
}

func (c *electionsClient) SubmitVote(ctx context.Context, in *Vote, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/Elections/SubmitVote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *electionsClient) Internal(ctx context.Context, opts ...grpc.CallOption) (Elections_InternalClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Elections_serviceDesc.Streams[0], "/Elections/Internal", opts...)
	if err != nil {
		return nil, err
	}
	x := &electionsInternalClient{stream}
	return x, nil
}

type Elections_InternalClient interface {
	Send(*Vote) error
	Recv() (*StatsVote, error)
	grpc.ClientStream
}

type electionsInternalClient struct {
	grpc.ClientStream
}

func (x *electionsInternalClient) Send(m *Vote) error {
	return x.ClientStream.SendMsg(m)
}

func (x *electionsInternalClient) Recv() (*StatsVote, error) {
	m := new(StatsVote)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ElectionsServer is the server API for Elections service.
type ElectionsServer interface {
	SubmitVote(context.Context, *Vote) (*empty.Empty, error)
	Internal(Elections_InternalServer) error
}

// UnimplementedElectionsServer can be embedded to have forward compatible implementations.
type UnimplementedElectionsServer struct {
}

func (*UnimplementedElectionsServer) SubmitVote(ctx context.Context, req *Vote) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitVote not implemented")
}
func (*UnimplementedElectionsServer) Internal(srv Elections_InternalServer) error {
	return status.Errorf(codes.Unimplemented, "method Internal not implemented")
}

func RegisterElectionsServer(s *grpc.Server, srv ElectionsServer) {
	s.RegisterService(&_Elections_serviceDesc, srv)
}

func _Elections_SubmitVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Vote)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ElectionsServer).SubmitVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Elections/SubmitVote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ElectionsServer).SubmitVote(ctx, req.(*Vote))
	}
	return interceptor(ctx, in, info, handler)
}

func _Elections_Internal_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ElectionsServer).Internal(&electionsInternalServer{stream})
}

type Elections_InternalServer interface {
	Send(*StatsVote) error
	Recv() (*Vote, error)
	grpc.ServerStream
}

type electionsInternalServer struct {
	grpc.ServerStream
}

func (x *electionsInternalServer) Send(m *StatsVote) error {
	return x.ServerStream.SendMsg(m)
}

func (x *electionsInternalServer) Recv() (*Vote, error) {
	m := new(Vote)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Elections_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Elections",
	HandlerType: (*ElectionsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitVote",
			Handler:    _Elections_SubmitVote_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Internal",
			Handler:       _Elections_Internal_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "elections.proto",
}
