// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: elections.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Vote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Passport      string                 `protobuf:"bytes,1,opt,name=passport,proto3" json:"passport,omitempty"`
	CandidateId   uint32                 `protobuf:"varint,2,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	Note          string                 `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vote) Reset() {
	*x = Vote{}
	mi := &file_elections_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vote) ProtoMessage() {}

func (x *Vote) ProtoReflect() protoreflect.Message {
	mi := &file_elections_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vote.ProtoReflect.Descriptor instead.
func (*Vote) Descriptor() ([]byte, []int) {
	return file_elections_proto_rawDescGZIP(), []int{0}
}

func (x *Vote) GetPassport() string {
	if x != nil {
		return x.Passport
	}
	return ""
}

func (x *Vote) GetCandidateId() uint32 {
	if x != nil {
		return x.CandidateId
	}
	return 0
}

func (x *Vote) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *Vote) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

type Stats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       map[uint32]uint32      `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stats) Reset() {
	*x = Stats{}
	mi := &file_elections_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stats) ProtoMessage() {}

func (x *Stats) ProtoReflect() protoreflect.Message {
	mi := &file_elections_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stats.ProtoReflect.Descriptor instead.
func (*Stats) Descriptor() ([]byte, []int) {
	return file_elections_proto_rawDescGZIP(), []int{1}
}

func (x *Stats) GetRecords() map[uint32]uint32 {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *Stats) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

var File_elections_proto protoreflect.FileDescriptor

const file_elections_proto_rawDesc = "" +
	"\n" +
	"\x0felections.proto\x12\x13elections_with_stat\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x89\x01\n" +
	"\x04Vote\x12\x1a\n" +
	"\bpassport\x18\x01 \x01(\tR\bpassport\x12!\n" +
	"\fcandidate_id\x18\x02 \x01(\rR\vcandidateId\x12\x12\n" +
	"\x04note\x18\x03 \x01(\tR\x04note\x12.\n" +
	"\x04time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\"\xb6\x01\n" +
	"\x05Stats\x12A\n" +
	"\arecords\x18\x01 \x03(\v2'.elections_with_stat.Stats.RecordsEntryR\arecords\x12.\n" +
	"\x04time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x1a:\n" +
	"\fRecordsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x012\x92\x01\n" +
	"\tElections\x12A\n" +
	"\n" +
	"SubmitVote\x12\x19.elections_with_stat.Vote\x1a\x16.google.protobuf.Empty\"\x00\x12B\n" +
	"\bGetStats\x12\x16.google.protobuf.Empty\x1a\x1a.elections_with_stat.Stats\"\x000\x01B\aZ\x05./;pbb\x06proto3"

var (
	file_elections_proto_rawDescOnce sync.Once
	file_elections_proto_rawDescData []byte
)

func file_elections_proto_rawDescGZIP() []byte {
	file_elections_proto_rawDescOnce.Do(func() {
		file_elections_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_elections_proto_rawDesc), len(file_elections_proto_rawDesc)))
	})
	return file_elections_proto_rawDescData
}

var file_elections_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_elections_proto_goTypes = []any{
	(*Vote)(nil),                  // 0: elections_with_stat.Vote
	(*Stats)(nil),                 // 1: elections_with_stat.Stats
	nil,                           // 2: elections_with_stat.Stats.RecordsEntry
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 4: google.protobuf.Empty
}
var file_elections_proto_depIdxs = []int32{
	3, // 0: elections_with_stat.Vote.time:type_name -> google.protobuf.Timestamp
	2, // 1: elections_with_stat.Stats.records:type_name -> elections_with_stat.Stats.RecordsEntry
	3, // 2: elections_with_stat.Stats.time:type_name -> google.protobuf.Timestamp
	0, // 3: elections_with_stat.Elections.SubmitVote:input_type -> elections_with_stat.Vote
	4, // 4: elections_with_stat.Elections.GetStats:input_type -> google.protobuf.Empty
	4, // 5: elections_with_stat.Elections.SubmitVote:output_type -> google.protobuf.Empty
	1, // 6: elections_with_stat.Elections.GetStats:output_type -> elections_with_stat.Stats
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_elections_proto_init() }
func file_elections_proto_init() {
	if File_elections_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_elections_proto_rawDesc), len(file_elections_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_elections_proto_goTypes,
		DependencyIndexes: file_elections_proto_depIdxs,
		MessageInfos:      file_elections_proto_msgTypes,
	}.Build()
	File_elections_proto = out.File
	file_elections_proto_goTypes = nil
	file_elections_proto_depIdxs = nil
}
